apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: my-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deploymentreact
  minReplicas: 3
  maxReplicas: 50
  targetCPUUtilizationPercentage: 65